spring.datasource.url=jdbc:mysql://${MYSQLHOST:autorack.proxy.rlwy.net}:${MYSQLPORT:27306}/${MYSQLDATABASE:railway}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:rMPUVgzSshxTuiIhPIHWzkEwtKIvJPfd}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=${PORT:8081}

# Custom properties
trilink.jwt.secret=9a4f2c8d3b7e1f6g5h4i3j2k1l0m9n8o7p6q5r4s3t2u1v0wxy
trilink.jwt.expiration=86400000
